### ISSUE TITLE
Auth breakage from MongoEngine / pymongo downgrade

### ISSUE THREAD

**Issue by ckane** [crits/crits#933]
In #932 it seems like pymongo was downgraded to 2.8.1 and mongoengine was downgraded to 0.8.8. This seems to have introduced a bug that causes the POST to /login/ to fail with a 500 in my environment. I'll try attempting to figure out where the breakage is occurring, but right now it is in the XMLHttpRequest right after pressing login. It seems to only happen when you get the user's password correct, and it prevents creation of an authentication session.

I tried blowing away the DB and starting from scratch - no help.

I reverted the change from #932 and then it began to work again.

Curious what the benefit (beyond "it's faster") of moving back to a 2-year-old version of mongoengine is for us. It seems like it will introduce legacy maintenance headaches...

**Comment by mgoffin** [comment]
20+s load times is unacceptable. Until such a time as we can support newer versions of the libraries without introducing slowness that makes the application almost unusable, we shouldn't upgrade.

The slowness was introduced in mongoengine. I am all for moving completely away from mongoengine and onto something more flexible if it means keeping the same speed (or better) and continuing to support newer versions of the libraries that are out.

**Comment by Cimabue** [comment]
+1 mgoffin. 
I use CRITs 4-6 hrs a day, and would shoot myself if I had to wait 20s for a page load. I get bent out of shape when it takes more than 5s for a page load.

**Comment by ckane** [comment]
Ah, I didn't realize the load-time penalty introduced was so large. I will just try blowing everything away on my dev environment and see if that fixes the auth breakage for me.

**Comment by mgoffin** [comment]
Are you using master? If so, check out the PR I recently pushed to sort out some issues with Roles. It has a spot in it where I fixed a 500 error for authentication.

**Comment by ckane** [comment]
Ah well, I will look at that then - that is my problem - 500 Error when correct password is given.

**Comment by ckane** [comment]
So, from what I can tell is this - the 500 error is being caused by an "<code>unrecognized write concern field: write_concern</code>" Exception that is thrown during the call to `request.session.cycle_key()` in crits/core/handlers.py 'login_user()'

The `remove()` in pymongo's collection.py is called, and this code ends up populating `command['writeConcern']` with `{'write_concern': {}}`, rather than `{'w': None}`. When I test for this error case in that code (in pymongo/collection.py), and rewrite `command['writeConcern'] = {'w': None}` the logins start working again.

I have blown away the entire crits db and also created a fresh Python virtualenv that I populated with the requirements in crits/requirements.txt.

**Comment by mgoffin** [comment]
Does setting a manual write concern in database.py or custom_settings.py fix it?

**Comment by ckane** [comment]
ok looks like if I add a line manually setting it after the MongoClient instantiation, the logins appear to be working.

```python
# Get config from DB
c = MongoClient(MONGO_HOST, MONGO_PORT, ssl=MONGO_SSL)
c.write_concern = {'w': 0, 'j': False} # ADDED THIS LINE, CAN NOW LOG IN
db = c[MONGO_DATABASE]
```

However, on logout - I get the error too, it turns out, and this doesn't fix that. Again, seems to be in how mongoengine is calling delete.

I'm curious though, if it being passed through debug_toolbar_mongo/operation_tracker.py `_remove` function, might be causing the write_concern field to be mishandled when it is being passed through to pymongo's collection.py `remove` function.

**Comment by mgoffin** [comment]
Weird. What if you remove the toolbar? I have all of this installed locally on my latest PR and I have no issues logging in (though the point of my PR is to move ACL into the database and to fix the previously mentioned login issue).

**Comment by ckane** [comment]
I removed the toolbar and it seems to have fixed the problem on log in, but on log out I still get the exception thrown... though that's being caused by the delete/remove pymongo call tearing down the session in mongodb

**Comment by ckane** [comment]
ignore my last comment - I misunderstood what you asked... I'll get back to you

**Comment by ckane** [comment]
Yes, never mind, making the above change in `settings.py` did not fix it. I had another change, that I forgot to back out, to bypass the session key cycling that allowed me to get in.

**Comment by ckane** [comment]
So, from what I can tell the problem I'm encountering seems to occur as a result of mongoengine v0.8.8 in file `mongoengine/queryset/base.py`, line `402`:

```python
queryset._collection.remove(queryset._query, write_concern=write_concern)
```

The error is that `write_concern=write_concern` should be passed like kwargs as `**write_concern`` in order for the call to work (according to `pymongo.collection.Collection.remove`).

It seems that this call was later rewritten as follows (in mongoengine 0.10.0+):
```python
queryset._collection.remove(queryset._query, **write_concern)
```

If I manually change the line in 0.8.8 `mongoengine/queryset/base.py` it seems to overcome my problems.

Complicating fixing this upstream, it appears that this particular file (mongoengine/queryset/base.py) was never actually added into the "0.8" branch in mongoengine's GitHub repository...despite it being distributed in the v0.8.8 release tarball.

**Comment by apolkosnik** [comment]
Good luck, I tried to fix a stupid import on 0.8.8 and they gave me a
finger.

**Comment by ckane** [comment]
Well, nice thing about GitHub is I can fork the project and make my own changes:
https://github.com/ckane/mongoengine-crits/tree/0.8-fix-write_concern

**Comment by apolkosnik** [comment]
Coleman,

They had 0.8.8 under a tag rather than a branch.

https://github.com/MongoEngine/mongoengine/tree/v0.8.8

My PR that was trying to fix an import and sync the 0.8 branch up.
https://github.com/MongoEngine/mongoengine/pull/1261

If you are going to fork, you might want to incorporate the "import fix"
that's mentioned there in order to allow it to work on Django 1.9.

Thanks,
-A




On Sep 18, 2017 12:42, "Coleman Kane" <notifications@github.com> wrote:

Well, nice thing about GitHub is I can fork the project and make my own
changes:
https://github.com/ckane/mongoengine-crits/tree/0.8-fix-write_concern

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/crits/crits/issues/933#issuecomment-330281762>, or mute
the thread

**Comment by ckane** [comment]
Thanks @apolkosnik that's hugely helpful - I basically forked from that tag and then cherry-picked the fix from their master branch. I can try doing the same for your import fix(es) and let you know how it goes.

I also appreciate the MongoEngine rant at the bottom of that issue. The more I mire myself in MongoEngine the less I like it.

Also every day that goes by I dislike the strong tie of CRITs with MongoDB more and more.

**Comment by mgoffin** [comment]
@ckane i think i submitted an issue a long while ago about moving away from mongoengine, and building a database abstraction layer such that people can submit their own database plugin for working with CRITs. Then it can run on basically anything people write the plugins for.

**Comment by ckane** [comment]
Yep @mgoffin I recall, actually #854 came up in discussion with my team this week. I completely agree with that approach.

**Comment by ZaneHintzman** [comment]
I'm having this same issue, and made the same observation that there's an error with `write_concern` in `mongoengine/queryset/base.py`. I just pulled the latest changes in the master branch, and am using mongoengine version 0.8.8 and pymongo version 2.8.1, but I still get this error. I modified the file as suggested, but then I got the same problem as #951. I wonder how other people using the latest code are avoiding these issues with the suggested versions of mongoengine and pymongo.

**Comment by ckane** [comment]
Install the version of mongoengine I have cloned here: https://github.com/ckane/mongoengine-crits/tree/0.8-fix-write_concern

I usually use Python virtualenvwrapper to run crits inside of, and then install the above, so I don't have to interfere with the rest of the system
